/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
  }
}
